from adafruit_hid.keycode import Keycode

key_maps = {
    1: {
        "Name": "MacOS",
        0: ([Keycode.COMMAND, Keycode.X], "Cut"),
        1: ([Keycode.COMMAND, Keycode.C], "Copy"),
        2: ([Keycode.COMMAND, Keycode.V], "Paste"),
        3: ([Keycode.COMMAND, Keycode.Z], "Undo"),
        4: ([Keycode.COMMAND, Keycode.SHIFT, Keycode.Z], "Redo"),
        5: ([Keycode.OPTION, Keycode.COMMAND, Keycode.ESCAPE], "Quit"),
        6: ("", ""),
        7: ("", ""),
        8: ("", ""),
        9: ("", ""),
        10: ("", ""),
        11: ("", ""),
    },
    2: {
        "Name": "Windows",
        0: ([Keycode.CONTROL, Keycode.X], "Cut"),
        1: ([Keycode.CONTROL, Keycode.C], "Copy"),
        2: ([Keycode.CONTROL, Keycode.V], "Paste"),
        3: ([Keycode.CONTROL, Keycode.Z], "Undo"),
        4: ([Keycode.CONTROL, Keycode.SHIFT, Keycode.ESCAPE], "Task"),
        5: ("", ""),
        6: ("", ""),
        7: ("", ""),
        8: ("", ""),
        9: ("", ""),
        10: ("", ""),
        11: ("", ""),
    },
    3: {
        "Name": "Git",
        0: ("git status\n", "status"),
        1: ("git diff\n", "diff"),
        2: ("git pull\n", "pull"),
        3: ('git commit -m "', "commit"),
        4: ("git push\n", "push"),
        5: ("", ""),
        6: ("", ""),
        7: ("", ""),
        8: ("", ""),
        9: ("", ""),
        10: ("", ""),
        11: ("", ""),
    },
}
