from adafruit_hid.keycode import Keycode

key_maps = {
    1: {
        "Name": "MacOS",
        0: ([Keycode.COMMAND, Keycode.X], "Cut"),
        1: ([Keycode.COMMAND, Keycode.C], "Copy"),
        2: ([Keycode.COMMAND, Keycode.V], "Paste"),
        3: ([Keycode.COMMAND, Keycode.Z], "Undo"),
        4: ([Keycode.COMMAND, Keycode.SHIFT, Keycode.Z], "Redo"),
        5: ([Keycode.OPTION, Keycode.COMMAND, Keycode.ESCAPE], "Quit"),
        6: ("", ""),
        7: ("", ""),
        8: ("", ""),
        9: ("", ""),
        10: ("", ""),
        11: ("", ""),
    },
    2: {
        "Name": "Windows",
        0: ([Keycode.CONTROL, Keycode.X], "Cut"),
        1: ([Keycode.CONTROL, Keycode.C], "Copy"),
        2: ([Keycode.CONTROL, Keycode.V], "Paste"),
        3: ([Keycode.CONTROL, Keycode.Z], "Undo"),
        4: ([Keycode.CONTROL, Keycode.SHIFT, Keycode.ESCAPE], "Task"),
        5: ("", ""),
        6: ("", ""),
        7: ("", ""),
        8: ("", ""),
        9: ("", ""),
        10: ("", ""),
        11: ("", ""),
    },
    3: {
        "Name": "Git",
        0: ("git status\n", "status"),
        1: ("git diff\n", "diff"),
        2: ("git pull\n", "pull"),
        3: ('git commit -m "', "commit"),
        4: ("git push\n", "push"),
        5: ("", ""),
        6: ("", ""),
        7: ("", ""),
        8: ("", ""),
        9: ("", ""),
        10: ("", ""),
        11: ("", ""),
    },
    4: {
        "Name": "Numpad",
        0: (Keycode.SEVEN, "7"),
        1: (Keycode.EIGHT, "8"),
        2: (Keycode.NINE, "9"),
        3: (Keycode.FOUR, "4"),
        4: (Keycode.FIVE, "5"),
        5: (Keycode.SIX, "6"),
        6: (Keycode.ONE, "1"),
        7: (Keycode.TWO, "2"),
        8: (Keycode.THREE, "3"),
        9: (Keycode.ZERO, "0"),
        10: (Keycode.PERIOD, "."),
        11: (Keycode.ENTER, "Enter"),
    },
    5: {
        "Name": "Alt Numpad",
        0: (Keycode.HOME, "Home"),
        1: (Keycode.UP_ARROW, "Up"),
        2: (Keycode.PAGE_UP, "PgUp"),
        3: (Keycode.LEFT_ARROW, "Left"),
        4: ("", ""),
        5: (Keycode.RIGHT_ARROW, "Right"),
        6: (Keycode.END, "End"),
        7: (Keycode.DOWN_ARROW, "Down"),
        8: (Keycode.PAGE_DOWN, "PgDn"),
        9: (Keycode.INSERT, "Ins"),
        10: (Keycode.DELETE, "Del"),
        11: (Keycode.ENTER, "Enter"),
    },
    6: {
        "Name": "Rick Roll",
        0: ("Never gonna give you up\n","1"),
        1: ("Never gonna let you down\n","2"),
        2: ("Never gonna run around and desert you\n","3"),
        3: ("Never gonna make you cry\n","4"),
        4: ("Never gonna say goodbye\n","5"),
        5: ("Never gonna tell a lie and hurt you\n","6"),
        6: ("https://www.youtube.com/watch?v=dQw4w9WgXcQ\n","YouTube"),
        7: ("", ""),
        8: ("", ""),
        9: ("", ""),
        10: ("", ""),
        11: ("", ""),    
    }
}
